name: Test Aliases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Debug Environment
      run: |
        echo "Shell: $SHELL"
        echo "PWD: $(pwd)"
        echo "PATH: $PATH"
        echo "Contents of current directory:"
        ls -la
        echo "Shell version:"
        sh --version || echo "sh version not available"
    
    - name: Install GitHub CLI
      run: |
        echo "Installing GitHub CLI..."
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh
        echo "GitHub CLI version:"
        gh --version

    - name: Make scripts executable
      run: |
        echo "Making scripts executable..."
        find . -type f -name "*.sh" -exec chmod +x {} \;
        echo "Verifying permissions:"
        find . -type f -name "*.sh" -ls
    
    - name: Install aliases
      run: |
        echo "Installing aliases..."
        ./scripts/install-aliases.sh 2>&1
        echo "Verifying gh aliases:"
        gh alias list
    
    - name: Run tests
      run: |
        echo "Running tests..."
        for test_file in tests/integration/*.test.sh; do
          echo "\n=== Running test file: $test_file ==="
          # Run with -e to exit on error and capture both stdout and stderr
          sh -ex "$test_file" 2>&1
          test_status=$?
          echo "Test exit status: $test_status"
          if [ $test_status -ne 0 ]; then
            echo "Test failed: $test_file"
            exit $test_status
          fi
        done 